spring:
    data:
        mongodb:
            host: 127.0.0.1
            database: test
            port: 27017
    
    security:
        user:
            name: admin
            password: admin
            roles: ADMIN

