pointer:
	gcc -o pointer.o -c pointer.c 
	gcc -o pointer pointer.o
	.\pointer.exe 

datatyp:
	gcc -o datentyp.o -c datentyp.c 
	gcc -o datentyp datentyp.o
	.\datentyp.exe

addwhile:
	gcc -o addwhile.o -c addwhile.c 
	gcc -o addwhile addwhile.o
	.\addwhile.exe

sum:
	gcc -o sum.o -c sum.c 
	gcc -o sum sum.o
	.\sum.exe

matlab:
	gcc -o matlab.o -c matlab.c 
	gcc -o matlab matlab.o
	.\matlab.exe

product:
	gcc -o product.o -c product.c 
	gcc -o product product.o
	.\product.exe


 xhochx1:
	gcc -o xhochx1.o -c xhochx1.c 
	gcc -o xhochx1 xhochx1.o
	.\xhochx1.exe


 montecarlo:
	gcc -o montecarlo.o -c montecarlo.c 
	gcc -o montecarlo montecarlo.o
	.\montecarlo.exe

 sinus:
	gcc -o sinus.o -c sinus.c 
	gcc -o sinus sinus.o
	.\sinus.exe

string:
	gcc -o string.o -c string.c 
	gcc -o string string.o
	.\string.exe

nullstelle:
	gcc -o nullstelle.o -c nullstelle.c 
	gcc -o nullstelle nullstelle.o
	.\nullstelle.exe

bubble:
	gcc -o bubble.o -c bubble.c 
	gcc -o bubble bubble.o
	.\bubble.exe

aritchFormater:
	gcc -c arithFormater.c
	gcc arithFormater.o
	.\a.exe

clean:
	rm *.o *.exe